language: python

# Run jobs on container-based infrastructure, can be overridden per job

env: FC=gfortran

branches:
  only:
    - master
    - dev

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.6
    - os: osx
      language: generic
      env: PYTHON_VER=3.7

    - os: linux
      language: generic  # No need to set Python version since its conda
      env: PYTHON_VER=3.6
    - os: linux
      language: generic
      env: PYTHON_VER=3.7
      
before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V
  
addons:
  apt:
    packages:
      - gfortran

install: 

    # Create test environment for package
  - python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/test_env.yaml
    # Activate the test environment
  - conda activate test
    # Build and install package
  - python setup.py develop --no-deps
  - conda install sphinx sphinx_rtd_theme
  - conda install sphinx-argparse


script:
#  - travis_wait pytest -v --cov=despasito despasito/tests/
    # Extend waittime to 30 min
  - travis_wait 75 pytest -v --cov=despasito despasito/tests/
  - cd docs
  - make html
  - cd ../

notifications:
    email: false

after_success:
  - codecov