language: python
python:
    - "2.7"
    - "3.6"
    - "3.9"

branches:
    only:
        - master

sudo: false

install:
    - pip install sphinx
    - pip install -r requirements-travis.txt

script:
    - inspekt checkall --disable-style E501,E265,W601,E402,E722,E741 --enable-lint W0611,W1201 --no-license-check