language: python
python:
  "3.8"
cache: pip

addons:
  chrome: stable
  
before_install:
  - export LANGUAGE=en_GB.UTF-8

install:
  - |
    latest=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
    wget https://chromedriver.storage.googleapis.com/$latest/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$(pwd)
  - chmod +x chromedriver
  - pip install -r requirements.txt
  - pip install coveralls codeclimate-test-reporter pycodestyle

before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - python manage.py collectstatic --noinput

script:
  - pycodestyle . --exclude=migrations,importer*
  - python manage.py check
  - python manage.py makemigrations --check --dry-run
  - coverage run manage.py test --verbosity=2

after_success:
  - coveralls
  - codeclimate-test-reporter

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify