---
dist: bionic

language: python

# Run tests against each supported version while docs and style are only
# considered on the latest supported version.
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38,docs,style

install:
  - pip install tox

script:
  - tox