language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
dist: focal
addons:
  postgresql: "13"
  apt:
    packages:
     - postgresql-13
install:
- pip install .
before_script:
- ssh-keygen -f ~/.ssh/id_rsa -N ""
- cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
- ssh -o StrictHostKeyChecking=no localhost id
script:
- py.test tests
notifications:
  irc:
    channels:
      - "irc.freenode.org#bundlewrap"
    use_notice: true
    skip_join: true