language: python
sudo: required
os:
  - linux
cache:
  pip: true
python:
  # - "3.4"
  - "3.5"
  - "3.6"
  # - "nightly"
before_install:
  - sudo apt-get install libspatialindex-dev
install:
  - pip install flake8
  - pip install .
script:
  - flake8 . --ignore=E501 --select=B,C,E,F,W,T4,B9 --exclude=docs,build
  - pytest 
# after_success:
#  - coveralls