language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "2.7"

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -e .[dev]
  - pip install tox-travis

  # command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install:
# command to run tests, e.g. python setup.py test
script:
  - tox

notifications:
  email: false