language: python
python:
    - "3.9"

install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - pip install coveralls

script:
    - py.test

after_success:
    - coveralls