dist: focal
language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "pypy3"
install: pip install Markdown pymdown-extensions docutils textile pygments codecov
script: coverage run setup.py test
after_success: codecov