language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - nightly
  - pypy
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=ant setup.py test
  - python setup.py build
after_success:
  - coveralls
matrix:
  allow_failures:
    - python: nightly