# Config file for automatic testing at travis-ci.org

sudo: required
language: python
dist: xenial

matrix:
  include:
  - python: "3.6"
  - python: "3.7"
  # Run a separate job for combined code quality checks & build tests
  - python: "3.8"
    env: TOXENV=coverage,mypy,style,docs,dist-test
  # Only this job will contain an encrypted PYPI_TOKEN for deployment
  - python: "3.8"
    env:
      - secure: QFRSBbtAPfFxO2GONfI2KCrq7gdSI6zj4wI5QEunjz8xVjvb60TD2Q4ULmoMPBqgFkqV6NZr6bB49MpNcpfw9aeBkUqjYmWWkLfZZsFWvJeRnkPV4EcfmMKJ9pph9QUYQ1BUcqWPZbPYk0VQdDxMVwDKETW2nzVNgRFaJm4O9kM6qV462/3dN53Q0NNTBfSju80nV8YQycP7onEQQILFityDOThKqR3FctDiwrfMo3ALWSfghkyvCgvrvpf6uAWncM1hwDwga+1Luo3vDG6reDE+M3AitFwo5XsPXy8hER8BwuUh8MRrr/HbakH66e83vvBX593DoGZr7UMqwEg+Xzpa2yUvSszW2U9ksh9BaYPbZG3nzsJJlTg61k6Sh7OU4AXglsDBPVX5aoLVz6XSAL97p+Ec85yo8dzpxzBc31ow8rI6JS9yycRnHXGATKqTIQ7Z3QiVaNKrIJVKhMdqvng1zb8RFR49MbPFT5QQuxOJLe/S1qkzOjclp2scZV17TPa6hkfTuDz01+rPXKh3US0WbR689TtNCBB/UwuoX5vnFqcvmqi0sZtl0G4eqXPvik4r7JnuX3d81LIGzF6e45FyO8sSvicZxCu8KmQQ7xI0hXjP6+vfEOnnz4xpAKmHmf2xTIStpuaCm7xqdt3M070P/A4kC0xBGcbcNCq1xU4=
  - python: "3.9"

# Install dependencies, run tests, and run coveralls after 'coverage' job
install: pip install ".[build]"
script: tox
after_success: if [[ $TOXENV == *"coverage"* ]]; then coveralls; fi

# Note: These two release types could be combined, but requires a long, ugly custom condition
# See: https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
deploy:
  # Stable releases: only git tags on master branch
  - provider: pypi
    user: __token__
    password: $PYPI_TOKEN
    distributions: sdist bdist_wheel
    skip_cleanup: true          # Don't delete build artifacts
    skip_existing: true         # Don't overwrite an existing package with the same name
    on:
      tags: true
      condition: $PYPI_TOKEN    # Only run in the job containing an encrypted PYPI_TOKEN
  # Pre-releases: dev branch only; pre-release version number is set in __init__.py
  - provider: pypi
    user: __token__
    password: $PYPI_TOKEN
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_existing: true
    on:
      branch: dev
      condition: $PYPI_TOKEN