language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
dist: trusty
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: "pip install peewee flask wtforms wtf-peewee"
script: "python runtests.py"