os: linux
dist: bionic
language: python

jobs:
  include:
    - name: "MTGJSON5 Tox - Python 3.6"
      before_install:
        - "pip install -U pip setuptools wheel tox-travis"
      install: "pip install -r requirements_test.txt"
      script: tox
      python: "3.6"

    - name: "MTGJSON5 Tox - Python 3.7"
      before_install:
        - "pip install -U pip setuptools wheel tox-travis"
      install: "pip install -r requirements_test.txt"
      script: tox
      python: "3.7"

    - name: "MTGJSON5 Tox - Python 3.8"
      before_install:
        - "pip install -U pip setuptools wheel tox-travis"
      install: "pip install -r requirements_test.txt"
      script: tox
      python: "3.8"