language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=1.11
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -e .[flake8,tests]
script:
  - flake8
  - pytest