sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36
    - os: linux
      dist: xenial
      python: 3.7
      env: TOXENV=py37
      sudo: true
    - python: "3.6"
      env: TOXENV=lint
cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox
language: python
script:
  - tox
notifications:
  email: false