language: python
python:
- '3.6'
install:
- pip install --upgrade -e . -r ./requirements/dev
script:
- export BOTO_CONFIG=/dev/null
- pytest --cov=checkQC tests/
after_success:
- codecov
notifications:
  email: false
deploy:
  provider: pypi
  username: __token__
  password:
    secure: a143I6FlaXYSdcOmXPkc4ZuMFJqLgiP9C/0p0S8pB/wTKwQ+ZN6zjhjuig2QYkEpine4o2vWzQsSqDjjOIrYjGRGM+58nwXhMI6h73le6zfnri52VsuLZMhgrjGkPEtE0ToYc7ZX36TFB6JlkfLUXgnVqTDP4r7AfUoVQc8T5WCZ2TbUsSNhTiQMtso0oH5CuaFPGlho2yhdrTmk6F4wJ4ljaLOpeUeBnXwvMHqEMyqHq2/Wwn3FRUXJp4UrA0ycX/x4OnofaEmc8hX4bTS/o2HJilDUYGtUkKuqGBiFU2h4x7tk1KSCIXPNVW3/apaIqNdPn4iEJA7NRxJ8oYfDimMSnVtsQtpaZm6rd3UZZ/Pq2GlgEUEQDenbU2QWudWC8WOLB5lVw2wea7AGyM+kgqfhxNp5vWNHgeUXxSuw0u1CI4+TktTWlTXHSJUd5UpNOhmyQqrf6f+3WkhtngP2E6iOiDER4JL5EeNaxKoCuyQby0v3br6afd0BIvfF8qA5NpZE+9VhW1LDRWQmp+Z/Tuit5Orex6NioQVguUd5mJcqWDtXF1k+PTUG7kkywVYmu9oYfzZg9ZDYP3koic7ELH1/846L7kgp4wTx7TN3L+z5UcAD6nLBeI8zqIDKVr+mIbYu9FK/D5kijbuA+QGvFrXcsSuTGjNO1eMZlVNOvR4=
  distributions: sdist bdist_wheel
  on:
    tags: true