os: linux
dist: xenial
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=black
    - python: 3.6
      env: TOXENV=elasticsearch
      services:
        - docker
      before_install:
        - docker pull elasticsearch:7.3.2
        - docker run --name elasticsearch -e "discovery.type=single-node" -p 9200:9200 -d elasticsearch:7.3.2
        - docker ps
        - sleep 60
install:
  - pip install tox
  - pip install codecov
script:
  - tox
after_success:
  - codecov