dist: xenial
sudo: required

language: python

addons:
  apt:
    packages:
      - libev-dev
      - libevent-dev

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  # Taken from https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-350497804
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

jobs:
  include:
    - python: 3.8
      env: TOX_ENV=py38
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.6
      env: TOX_ENV=docs
    - python: 3.6
      env: TOX_ENV=flake8
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.5
      env: TOX_ENV=py35

script:
    - tox -v -e $TOX_ENV

install:
    - pip install tox coveralls

after_success:
    - coveralls

notifications:
    email: tarek@mozilla.com
    irc: "irc.freenode.org#mozilla-circus"
    on_success: change