language: python

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=docs
    - python: 3.4
      env: TOXENV=py34-linux-package
    - python: 3.5
      env: TOXENV=py35-linux-package
    - python: 3.6
      env: TOXENV=py36-linux-package


install:
  - pip install tox
  - pip install .

script:
  - tox -v --skip-missing-interpreters

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aCLH0u+8i8YIhYEDsRTwcCCuIkfrRrUE/+n801oDkxfl80N6NqNeilEUpQ9uMQ5G00KlZSAyBNW3Ei+40F16nFChXsHs5hFze6Q/LRUItdOkxbG7etqbiP6523KpZDebYZYbYcN7zia3VczQDR9PwgiR9R2C4pm28QEqzC1htl4+GcI6UpH7hWCTo5zu/+gYX1zvysN4fC+gMPkNv6W8fskfywpX7l2LgZIujaiXzAvx6anbRdhJaJZG26DhDMV0xT2xU6pmC7/W5Q3NXBe4EjKass1vbhaJC66/Oi1SsaSV9YR4Lg17aG8Xqwf5mbA+M2g0LGyNdswNwamJ4R2z1J8qsOzghE0hWaCsEBsUKe/LuVSRZ0O5BVly7GNOC0KqBTKbvFm5Rfl2pykZnZFxwF3tVL0mhVhJ6b6HwBO9KSnXkN4EaJTieWVT96yImOJChMk64Q8t2jAGZXxTJeLzKmq1sBiDDRIqTJvD5xh7SO7OwNW02U2dRV2SMmtYq8bttp4VyzrG80QJCZae+VE4OGrPnFqG9gBMqaW0blULh5nZkaFJlnc3JXxjrzqa46ii4aC0C2l4FOQYjFhc9TAM+XRzw0qn9HqrooVKJ9f1pK0shT1nAukBPFiBpd10owYle06Z/9EHQHlcYfqnl4xT8oJrpkZtvd0zyZy3EDfmYBY=
  file: "stacks_py*_linux.pex"
  file_glob: true
  on:
    tags: true
    repo: cfstacks/stacks