os: linux



dist: bionic



language: python



python:

  - "3.7"

  - "3.8"

  - "3.9"

  - "3.10"



# TODO eventually I want a better build matrix here, i.a. for numpy versions



cache:

  pip: true

  directories:

    - "$HOME/.cache/pypoetry"



install:

  - pip install poetry

  - poetry install



git:

  depth: 3



branches:       # since the master branch is the only one where PRs are

  only:         # merged in.

    - master

    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/    # for release tags



script:

  - poetry run pytest

  - poetry run mypy alns



before_deploy:

  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS

  - poetry build



deploy:

  provider: script

  script: poetry publish

  skip_cleanup: true

  on:

    # Deploy to PyPI on tagged commits, from the latest Python version

    tags: true

    condition: "$TRAVIS_PYTHON_VERSION == 3.9"



after_success:

  - codecov
