os: linux
dist: focal

services:
  - docker

language: python
python:
  - '3.6'

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: test
      script: ./tests/run_tests.sh
    - stage: deploy
      script:
        - python setup.py install_egg_info sdist bdist_wheel
      deploy:
        provider: pypi
        username: '__token__'
        password: $PYPI_TOKEN
        on:
          branch: master

stages:
  - test
  - deploy