sudo: required
language: python
python:
  - "3.9"
  - "3.10-dev"  # development branch
services:
  - docker
before_install:
  - pip install -U docker-compose 
script: 
  - make bootstrap
  - make test