sudo: required  # for 3.7, see https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
language: python
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
jobs:
  include:
  - python: "3.8"
    env: TOXENV=lint
install: pip install tox-travis
script: tox