language: python
python:
    - "3.6"

branches:
    only:
        - master

sudo: false

install:
    - pip install sphinx${SPHINX_VERSION:+==$SPHINX_VERSION}
    - pip install -r requirements-travis.txt

script:
    - inspekt checkall --disable-style E501,E265,W601,W605,E402,E722,E741 --no-license-check