language: python
sudo: false

python:
 - '3.5'
 - '3.6'

cache:
  directories:
  - $HOME/.cache/pip

install:
 - pip install -r requirements/tests.txt
 - pip install coveralls

script:
 - nosetests --with-coverage --cover-erase --cover-package=temba_client
 - flake8

after_success:
 - coveralls

notifications:
  slack:
    secure: F6HxphE09WAOd1ux2oEzrgKAoyCLGqauqR/nH5vXHVFUZrKZHvGmhCPFKkLHJnpeNIE4l4xMtRAqNb5EuFJJzjO5myNJ2Ihx1pfYUJF+5GuYvWttpdRrPh6MSVmR3/oZWSKD67abrVKhX85zg4RNLz7RmblooSbPLa8Jj+p72/s=