language: python
python:
  - 3.7
  - 3.8
  - 3.9
os:
  - linux
env:
  global:
    - COV_THRESHOLD=95
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r dev-requirements.txt
script:
  - pytest sklearn_genetic/ --verbose --color=yes --assert=plain --cov-fail-under=$COV_THRESHOLD --cov-config=.coveragerc --cov=./ -p no:warnings
after_success:
  - codecov