language: python
sudo: false
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install codecov coverage
script:
- nosetests --verbose --with-coverage --cover-erase --cover-package=catkin_lint test
after_success:
  - codecov
