language: python
cache: pip
dist: xenial
sudo: required
os:
- linux
python:
- 3.6
install:
- pip install manticore[native]
- pip install nose
script:
- nosetests
notifications:
  slack:
    secure: IgNNg1xxbnGcum9aFwg2N1WbQkSp0lbkZMDg0xM5NUiOVjGRWPw8JpsjW4hOgi831wHEhtthwpQeSE4htfuuXAJ4XcOIoN/SGsYCK3wvFrwADJtbVXv7GoHmTuvkBnU9r2CthplMKkkZFaPGG2OL2S+JivD9KgGL0MUhz+q/tw11SaNrvlLj2ZwqFNlvoI7bXp3zm06yE/bNGtBLHmTqzj9eT4s5e/RB4QmnfHmf3a4cbXDRT20ki9rikUDIIz9kAZ1zdqbaJbv6AoawtSfkBVYUcJ7A7NeBRSrWR3n4s7SYWEo9FqC6dPJf4kEQuHeGkSZCkZpIbL+qEjmfiGV5+XNGjh2bqQSELh+3/okjHibWAF+y07PpvUGGOxeMIC+IS2kILv//cF3/bqIrPsEecZ1LK74stlw2w7Zshkm1hfswY/afs52yRrA0ZUt9FGf5VcVYbKs9VxkQgNIS8TrAHPBOPnAWkkQzYmhgfK9Y+fIWq29K5xbPJzXWtoetQU8boAd4fYNo38G8mqps7fVZhMznRipWY5Eu6ozktkvStH2obJ9/5tTx7Abs3dsFSkcbM7DQXF5zbnCm6ycjV14r1JMCe5AUkHbkukuUzO7lSL2oiXcfnnb4co/kWFv4WTfgv5FPbxDqpPT8tlnPOniS/EApl/SfcGGgt8I5hNVge40=